language: node_js
node_js:
  - 10.11.0

env:
  global:
    - APP_ENV=$APP_ENV

before_install:
  - npm i -g makeshift && makeshift -s @bcoe -r registry.npmjs.org

install:
  - npm install

script:
  - npm run test:prod
  - npm run build:prod

before_deploy:
  - cd dist/

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  keep-history: true
  on:
    branch: master
    tags: true
    repo: $GITHUB_REPO
