version: 2

defaults: &defaults
  working_directory: ~/tmp
  docker:
    - image: circleci/node:10.11.0

  environment:
    NODE_ENV: ${APP_ENV}

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Restore local dependencies from cache
      - restore_cache:
          keys: 
            - v1-dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install

      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Test the source code
      - run:
          name: Testing
          command: npm run test:prod

      # Test the source code
      - run:
          name: Building
          command: npm run build:prod

      - persist_to_workspace:
          root: ~/tmp
          paths: .

  create_artifact:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp

      - run:
          name: Creating Artifacts
          command: |
            mkdir /tmp/artifacts;
            zip -r /tmp/artifacts/dist-$CIRCLE_BUILD_NUM.zip dist/
            
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc

      - run:
          name: Publishing to NPM
          command: npm publish dist/

workflows:
  version: 2
  # Build and test
  build_and_publish:
    jobs:
      # Build application
      - build:
          filters:
            branches:
              only: master
      
      # Create and save artifact
      - create_artifact:
          requires:
            - build

      # Publish to NPM
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
